commands:
   - alias: s 
     command: |
          $1 &
          disown
   - alias: se
     command: |
          $1 & 
          disown
          exit
   - alias: nvimconf
     command: |
          cd ~/.config/nvim/lua
   - alias: dev
     command: |
          ~/startup/default
   - alias: dev-sv
     command: |
          ~/startup/svelte
   - alias: dev-gd
     command: |
          ~/startup/godot
   - alias: kill
     command: |
          tmux kill-session
   - alias: clone
     command: |
          git clone git@github.com:codevogel/$1.git
   - alias: clone-x
     command: |
          git clone git@github.com:$1/$2.git
   - alias: keeb-split
     command: |
          sudo cat /etc/default/keyboard-split | sudo tee /etc/default/keyboard > /dev/null
          sudo dpkg-reconfigure keyboard-configuration
   - alias: keeb-laptop
     command: |
          sudo cat /etc/default/keyboard-laptop | sudo tee /etc/default/keyboard > /dev/null
          sudo dpkg-reconfigure keyboard-configuration
   - alias: bright
     command: |
          sudo brightnessctl s $1
