commands:
   - alias: godot
     command: |
         /home/$(whoami)/work/godot/engine/Godot_v4.3-stable_linux.x86_64 -- -p & 
         disown
         wezterm start --always-new-process -- zsh -c "cd ~/runic-roots && nvim .; exec zsh" & 
         disown
         exit
   - alias: s 
     command: |
          $1 &
          disown
   - alias: se
     command: |
          $1 & 
          disown
          exit
   - alias: nvimconf
     command: |
          cd ~/.config/nvim/lua
   - alias: start-default
     command: |
          ~/startup/default $1
   - alias: start-web-portal
     command: |
          ~/startup/web-portal
